// Date: 7/31/2013 11:11:00 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Piece1;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Piece1.Shape2", 28, 0);
    setTextureOffset("Piece1.trig1", 10, 17);
    setTextureOffset("Piece1.Shape4", 0, 23);
    setTextureOffset("Piece1.trig0", 0, 21);
    
    Piece1 = new ModelRenderer(this, "Piece1");
    Piece1.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece1, 0F, 0F, 0F);
    Piece1.mirror = true;
      Piece1.addBox("Shape2", -4.5F, -4F, -4.5F, 9, 17, 9);
      Piece1.addBox("trig1", -1.5F, -5F, -7F, 3, 14, 1);
      Piece1.addBox("Shape4", -1.5F, -7F, -5F, 3, 3, 6);
      Piece1.addBox("trig0", -1.5F, -7.1F, -6F, 3, 4, 1);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Piece1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
